version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dbt
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: dbt
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: